// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for NodeType.
const (
	Leader   NodeType = "leader"
	Soldier  NodeType = "soldier"
	Vanguard NodeType = "vanguard"
)

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	Name string `json:"name"`

	// Ref Reference to an external secret store path.
	Ref *string `json:"ref,omitempty"`

	// Value Literal string value.
	Value *string `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetGitHubAccessTokenResponse defines model for GetGitHubAccessTokenResponse.
type GetGitHubAccessTokenResponse struct {
	// AccessToken The GitHub access token
	AccessToken string `json:"accessToken"`
}

// GetNodeConfigResponse defines model for GetNodeConfigResponse.
type GetNodeConfigResponse struct {
	// ServiceDeployments A list of all services assigned to this node with their final overridden configurations.
	ServiceDeployments []ServiceDeployment `json:"serviceDeployments"`
	Type               NodeType            `json:"type"`
}

// GetNodePingResponse defines model for GetNodePingResponse.
type GetNodePingResponse struct {
	// Status The current health status of Citadel
	Status string `json:"status"`

	// Timestamp The server time when the ping was processed
	Timestamp time.Time `json:"timestamp"`

	// Version The running version of the Citadel control plane
	Version *string `json:"version,omitempty"`
}

// NodeType defines model for NodeType.
type NodeType string

// ServiceDeployment defines model for ServiceDeployment.
type ServiceDeployment struct {
	// Branch The git branch derived from environment overrides.
	Branch     string `json:"branch"`
	DefVersion string `json:"defVersion"`
	GitUrl     string `json:"gitUrl"`

	// IngressHost Optional host mapping from environment overrides.
	IngressHost *string `json:"ingressHost,omitempty"`
	Kind        string  `json:"kind"`
	Name        string  `json:"name"`

	// Port The final overridden port number.
	Port      int     `json:"port"`
	RunScript *string `json:"runScript,omitempty"`
	Runtime   struct {
		Engine  string `json:"engine"`
		Version string `json:"version"`
	} `json:"runtime"`

	// Variables Final list of environment variables including secrets.
	Variables *[]EnvironmentVariable `json:"variables,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetGithubAccessToken request
	GetGithubAccessToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNodeIdGetConfig request
	GetNodeIdGetConfig(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNodeIdPing request
	GetNodeIdPing(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetGithubAccessToken(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetGithubAccessTokenRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNodeIdGetConfig(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNodeIdGetConfigRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNodeIdPing(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNodeIdPingRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetGithubAccessTokenRequest generates requests for GetGithubAccessToken
func NewGetGithubAccessTokenRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/github/access-token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNodeIdGetConfigRequest generates requests for GetNodeIdGetConfig
func NewGetNodeIdGetConfigRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/node/%s/get-config", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNodeIdPingRequest generates requests for GetNodeIdPing
func NewGetNodeIdPingRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/node/%s/ping", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetGithubAccessTokenWithResponse request
	GetGithubAccessTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetGithubAccessTokenResponse, error)

	// GetNodeIdGetConfigWithResponse request
	GetNodeIdGetConfigWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetNodeIdGetConfigResponse, error)

	// GetNodeIdPingWithResponse request
	GetNodeIdPingWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetNodeIdPingResponse, error)
}

type GetGithubAccessTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetGitHubAccessTokenResponse
	JSON401      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetGithubAccessTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetGithubAccessTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNodeIdGetConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetNodeConfigResponse
	JSON401      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNodeIdGetConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNodeIdGetConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNodeIdPingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetNodePingResponse
	JSON401      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetNodeIdPingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNodeIdPingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetGithubAccessTokenWithResponse request returning *GetGithubAccessTokenResponse
func (c *ClientWithResponses) GetGithubAccessTokenWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetGithubAccessTokenResponse, error) {
	rsp, err := c.GetGithubAccessToken(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetGithubAccessTokenResponse(rsp)
}

// GetNodeIdGetConfigWithResponse request returning *GetNodeIdGetConfigResponse
func (c *ClientWithResponses) GetNodeIdGetConfigWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetNodeIdGetConfigResponse, error) {
	rsp, err := c.GetNodeIdGetConfig(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNodeIdGetConfigResponse(rsp)
}

// GetNodeIdPingWithResponse request returning *GetNodeIdPingResponse
func (c *ClientWithResponses) GetNodeIdPingWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetNodeIdPingResponse, error) {
	rsp, err := c.GetNodeIdPing(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNodeIdPingResponse(rsp)
}

// ParseGetGithubAccessTokenResponse parses an HTTP response from a GetGithubAccessTokenWithResponse call
func ParseGetGithubAccessTokenResponse(rsp *http.Response) (*GetGithubAccessTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetGithubAccessTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetGitHubAccessTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetNodeIdGetConfigResponse parses an HTTP response from a GetNodeIdGetConfigWithResponse call
func ParseGetNodeIdGetConfigResponse(rsp *http.Response) (*GetNodeIdGetConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNodeIdGetConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetNodeConfigResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}

// ParseGetNodeIdPingResponse parses an HTTP response from a GetNodeIdPingWithResponse call
func ParseGetNodeIdPingResponse(rsp *http.Response) (*GetNodeIdPingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNodeIdPingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetNodePingResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	}

	return response, nil
}
