// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetAwsSecretResponse defines model for GetAwsSecretResponse.
type GetAwsSecretResponse struct {
	Entries *[]struct {
		Key   *string `json:"key,omitempty"`
		Value *string `json:"value,omitempty"`
	} `json:"entries,omitempty"`

	// PlainText Populated if it's a raw string
	PlainText *string `json:"plainText,omitempty"`
}

// GetGitHubAccessTokenResponse defines model for GetGitHubAccessTokenResponse.
type GetGitHubAccessTokenResponse struct {
	// AccessToken The GitHub access token
	AccessToken string `json:"accessToken"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Status The current health status of Citadel
	Status string `json:"status"`

	// Timestamp The server time when the ping was processed
	Timestamp time.Time `json:"timestamp"`

	// Version The running version of the Citadel control plane
	Version *string `json:"version,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve an AWS Secret
	// (GET /aws/secrets/{id})
	GetAwsSecretsId(c *gin.Context, id string)
	// Retrieve a GitHub access token
	// (GET /github/access-token)
	GetGithubAccessToken(c *gin.Context)
	// Check Citadel connectivity
	// (GET /ping)
	GetPing(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAwsSecretsId operation middleware
func (siw *ServerInterfaceWrapper) GetAwsSecretsId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAwsSecretsId(c, id)
}

// GetGithubAccessToken operation middleware
func (siw *ServerInterfaceWrapper) GetGithubAccessToken(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGithubAccessToken(c)
}

// GetPing operation middleware
func (siw *ServerInterfaceWrapper) GetPing(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPing(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/aws/secrets/:id", wrapper.GetAwsSecretsId)
	router.GET(options.BaseURL+"/github/access-token", wrapper.GetGithubAccessToken)
	router.GET(options.BaseURL+"/ping", wrapper.GetPing)
}
