// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for NodeType.
const (
	Leader   NodeType = "leader"
	Soldier  NodeType = "soldier"
	Vanguard NodeType = "vanguard"
)

// EnvironmentVariable defines model for EnvironmentVariable.
type EnvironmentVariable struct {
	Name string `json:"name"`

	// Ref Reference to an external secret store path.
	Ref *string `json:"ref,omitempty"`

	// Value Literal string value.
	Value *string `json:"value,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetGitHubAccessTokenResponse defines model for GetGitHubAccessTokenResponse.
type GetGitHubAccessTokenResponse struct {
	// AccessToken The GitHub access token
	AccessToken string `json:"accessToken"`
}

// GetNodeConfigResponse defines model for GetNodeConfigResponse.
type GetNodeConfigResponse struct {
	// ServiceDeployments A list of all services assigned to this node with their final overridden configurations.
	ServiceDeployments []ServiceDeployment `json:"serviceDeployments"`
	Type               NodeType            `json:"type"`
}

// GetNodePingResponse defines model for GetNodePingResponse.
type GetNodePingResponse struct {
	// Status The current health status of Citadel
	Status string `json:"status"`

	// Timestamp The server time when the ping was processed
	Timestamp time.Time `json:"timestamp"`

	// Version The running version of the Citadel control plane
	Version *string `json:"version,omitempty"`
}

// NodeType defines model for NodeType.
type NodeType string

// ServiceDeployment defines model for ServiceDeployment.
type ServiceDeployment struct {
	// Branch The git branch derived from environment overrides.
	Branch     string `json:"branch"`
	DefVersion string `json:"defVersion"`
	GitUrl     string `json:"gitUrl"`

	// IngressHost Optional host mapping from environment overrides.
	IngressHost *string `json:"ingressHost,omitempty"`
	Kind        string  `json:"kind"`
	Name        string  `json:"name"`

	// Port The final overridden port number.
	Port      int     `json:"port"`
	RunScript *string `json:"runScript,omitempty"`
	Runtime   struct {
		Engine  string `json:"engine"`
		Version string `json:"version"`
	} `json:"runtime"`

	// Variables Final list of environment variables including secrets.
	Variables *[]EnvironmentVariable `json:"variables,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a GitHub access token
	// (GET /github/access-token)
	GetGithubAccessToken(c *gin.Context)
	// Get node configuration with service deployments
	// (GET /node/{id}/get-config)
	GetNodeIdGetConfig(c *gin.Context, id string)
	// Send ping for the current node
	// (GET /node/{id}/ping)
	GetNodeIdPing(c *gin.Context, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetGithubAccessToken operation middleware
func (siw *ServerInterfaceWrapper) GetGithubAccessToken(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGithubAccessToken(c)
}

// GetNodeIdGetConfig operation middleware
func (siw *ServerInterfaceWrapper) GetNodeIdGetConfig(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNodeIdGetConfig(c, id)
}

// GetNodeIdPing operation middleware
func (siw *ServerInterfaceWrapper) GetNodeIdPing(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNodeIdPing(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/github/access-token", wrapper.GetGithubAccessToken)
	router.GET(options.BaseURL+"/node/:id/get-config", wrapper.GetNodeIdGetConfig)
	router.GET(options.BaseURL+"/node/:id/ping", wrapper.GetNodeIdPing)
}
