// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package main

import (
	"time"

	"github.com/gin-gonic/gin"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetGitHubAccessTokenResponse defines model for GetGitHubAccessTokenResponse.
type GetGitHubAccessTokenResponse struct {
	// AccessToken The GitHub access token
	AccessToken string `json:"accessToken"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Status The current health status of Citadel
	Status string `json:"status"`

	// Timestamp The server time when the ping was processed
	Timestamp time.Time `json:"timestamp"`

	// Version The running version of the Citadel control plane
	Version *string `json:"version,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a GitHub access token
	// (GET /github/access-token)
	GetGitHubAccessToken(c *gin.Context)
	// Check Citadel connectivity
	// (GET /ping)
	Ping(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetGitHubAccessToken operation middleware
func (siw *ServerInterfaceWrapper) GetGitHubAccessToken(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetGitHubAccessToken(c)
}

// Ping operation middleware
func (siw *ServerInterfaceWrapper) Ping(c *gin.Context) {

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Ping(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/github/access-token", wrapper.GetGitHubAccessToken)
	router.GET(options.BaseURL+"/ping", wrapper.Ping)
}
